name: Entrega Contínua
on:
  push:
    branches:
      - main

jobs:
  entrega:
    name: Entrega
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Upload Automático
        uses: actions/upload-artifact@v4
        with:
          name: rolandodados
          path: |
            *.py
            README.md

  implementacao:
    name: Implementacao
    runs-on: ubuntu-latest
    needs: Entrega
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: rolandodados
      - name: Display structure of downloaded files
        run: ls -R