name: Entrega Contínua
on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Upload Automático
        uses: actions/upload-artifact@v4
        with:
          name: rolandodados
          path: |
            *.py
            README.md

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: rolandodados
      - name: Display structure of downloaded files
        run: ls -R